### ISSUE TITLE
How hard to support 1.7.10?

### ISSUE THREAD

**Issue by richardhendricks** [jjtParadox/Barometer#3]
1.7.10 still gets lots of love, any chance this could be backported to 1.7.10? Thanks!

**Comment by jjtParadox** [comment]
I think it's doable. I'm not familiar with the 1.7.10 API and might screw things up if I attempt it, but I think only the [Barometer.kt](https://github.com/jjtParadox/Barometer/blob/master/src/main/kotlin/com/jjtparadox/barometer/Barometer.kt) file needs to be modified for the port.

If you'd like to try at backporting it, let me know! I'm very open to PRs :smile: 

(I'll close this issue in a week or two if there aren't any updates)
